[package]
name = "optim-simplex"
version = "0.1.0"
edition = "2024"

[dependencies]
highs = "1.12.0"
ndarray = { version = "0.16.1", features = ["rayon", "blas"] }
ndarray-linalg = "0.17.0"
rand = "0.9.2"
rayon = "1.11.0"
redis = "0.32.5"
sprs = "0.11.3"

